feat: add useCardAnimation
react-community/react-navigation pull request #11568
Opened 2023-08-30 13:16 UTC by adamgrzybowski

**Motivation**

Make animation progress available inside a screen.

**Test plan**

Describe the **steps to test this change** so that a reviewer can verify it. Provide screenshots or videos if the change affects UI.

The change must pass lint, typescript and tests.

2023-09-03 10:23 UTC, osdnk commented on packages/material-top-tabs/src/utils/useTabAnimation.tsx
> +      "Couldn't find values for card animation. Are you inside a screen in Tab?"
i believe it's worth clarifying that it's material-top-tabs (and not bottom-tabs).

2023-09-03 15:25 UTC, osdnk requested changes
Thanks for those changes. I think I need to suggest a slightly different API. In my opinion, we should target a similar API as `useCardAnimation`.

Particularly, I believe that in the future we may support multiple animations. In the same way, as we recently merged #11323, we can also imagine a similar animation inside `material-top-tabs`. 

Therefore, I would suggest making the API more open for multiple animations and returning an object, instead of just a single animated value. The current value may live under the `position` field in the object. With this approach, we will not be forced to make a breaking change (or design a weird API).

`const { position } = useTabAnimation()`

2023-09-03 17:51 UTC, osdnk commented on packages/material-top-tabs/src/utils/useTabAnimation.tsx
> +      "Couldn't find values for card animation. Are you inside a screen in Tab?"
Also, `card animation`? 😅

2023-09-04 14:29 UTC, adamgrzybowski commented
Hey @osdnk, I made some changes. Please take a look when you have a moment

2023-09-04 16:50 UTC, osdnk requested changes
I think maybe i was not clear about that. I think that the name `useCardAnimation` is not OK here - we don't have any card. `useTabAnimation` is ok.

`Couldn't find values for tab animation. Are you inside a screen in Material Top Tab navigator?` should be the message

2023-09-06 15:51 UTC, adamgrzybowski commented
@osdnk Yeah I can see it now 😄 idk why I understood it wrong. I pushed fixed version.

2023-09-06 15:52 UTC, osdnk approved these changes

2023-09-06 15:54 UTC, merged